### ISSUE TITLE
Explanation of period

### ISSUE THREAD

**Issue by anpr** [mloughran/api_cache#21]
Hi there,

I'm feeling pretty stupid, but could somebody (ideally you Martyn) explain the purpose of the :period attribute in the APICache options? 

In particular if the value is smaller than :cache (i.e. the time-to-live), as it is in the example given in the documentation. Isn't it the case then that if the API is hit more frequently than :period, the cache should simply be current? 

Or is the use case of :period that you want to avoid to call the API too frequently in case you manually invalidate the cache? Another idea: is this done to avoid concurrency issues, where many processes/threads simultaneously try to refetch a new value from the API in case the cached value's time-to-live is over?

**Comment by mloughran** [comment]
The main use case is that, if the API is not responding correctly, that it doesn't get swamped with requests (since failures do not get cached). So typically period would be smaller than cache.

There's nothing clever to around concurrency issues - eg threadsafe or multi process locking - so it's not a guarantee that the API could never be called more frequently, but it's probably good enough in most cases.

You're right - TTL might be a much better name for the parameter then cache. Even I find the names confusing now - but this gem was written a long time ago!

**Comment by anpr** [comment]
Thanks for the explanation
